version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn-lock.json" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: NODE_ENV=production yarn

      # Keep cache
      - save_cache:
          key: yarn-cache-{{ checksum "yarn-lock.json" }}
          paths:
            - "node_modules"

      # Lint
      - run:
          name: Lint
          command: yarn lint

      # Tests
      - run:
          name: Tests
          command: yarn test

      # Coverage
      - run:
          name: Coverage
          command: yarn codecov

      - store_test_results:
          path: test-results
