version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: NODE_ENV=production npm

      # Keep cache
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      # Lint
      - run:
          name: Lint
          command: npm run lint

      # Tests
      - run:
          name: Tests
          command: npm run jest

      # Coverage
      - run:
          name: Coverage
          command: npm run codecov

      - store_test_results:
          path: test-results
